---
# This is a comment.
# You can configure the sponsor button in your repository to include
# sponsored developers in GitHub Sponsors, external funding platforms,
# or a custom funding URL.

# More details are here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: fedejaure
