
.PHONY: install

install:
	./tools/install.sh

hooks:
	./tools/install_hooks.sh

flake8:
	pipenv run flake8 data-lake-api

run_server_dev:
	./tools/run_server_dev.sh

run_shell_dev:
	./tools/run_shell_dev.sh
